version: '3.4'

networks:
  dev:
    driver: bridge

services:
  customer-service:
    image: ${REGISTRY:-service-one}/customer-service.api:${PLATFORM:-linux}-${TAG:-latest}
    depends_on:
      - "customer_db"
    container_name: customer-service
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: services/ServiceOne/ServiceOne.API/Dockerfile
    environment:
      - ConnectionStrings_Postgres=host=worklog_management_db;port=5435;database=calculator;username=postgres;password=MrBen228;Pooling=true;
    networks:
      - dev

  customer_db:
    image: postgres:latest
    container_name: calculator_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MrBen228
      - POSTGRES_DB=calculator
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - customer_data:/var/lib/postgresql/data/
    networks:
      - dev

volumes:
  customer_data:
